---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

#<-- Uncomment this block for troubleshooting
# log:
# level: debug

#<-- Comment this block out for production
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    

providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    directory: /etc/traefik
    watch: true

certificatesResolvers:
#Use this resolver while in testing fase
  staging:
    acme:
      email: example@email.com
      storage: /var/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" #<-- Staging server 
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
#Use this resolver for production
  production:
    acme:
      email: example@email.com
      storage: /var/traefik/certs/acme.json
      caServer: " https://acme-v02.api.letsencrypt.org/directory" #<-- production server
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
